FROM node:latest

#RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app

ARG BACKEND_IP
ARG BACKEND_PORT

ENV VUE_APP_BACKEND_IP=$BACKEND_IP
ENV VUE_APP_BACKEND_PORT=$BACKEND_PORT

COPY frontend/*.json ./
COPY frontend/*.js ./
COPY frontend/src ./src/

#RUN echo "BACKEND_IP=$BACKEND_IP\nBACKEND_PORT=$BACKEND_PORT"> .env
RUN npm install
