services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: thermoSensorTS/latest
    command: "npm run serve --dev"
    ports:
       - "8080:8080" 
    depends_on:
      backend: 
        condition: service_started
        restart: true

  backend:
    build:
      context: .
      dockerfile: Dockerfile.rust
    image: thermoSensorRS/latest
    command: "./backend"
    depends_on:
      bt_probe: 
        condition: service_healthy
        restart: true
    volumes:
      - ./db:/db
    ports:
       - "8081:8081" #later we can link it internally need it for debugging right now

  bt_probe:
    build:
      context: .
      dockerfile: Dockerfile.rust
    image: thermoSensorRS/latest
    privileged: true 
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "dmesg | grep -q -i blue."]
      interval: 30s
      timeout: 10s
      retries: 20
    volumes:
      - /var/run/dbus/:/var/run/dbus/:z 
      - ./db:/db
    command: "./bt_data"

